@server = http://localhost:3000/

# POST {{server}}write/
# content-type: application/json

# {
#     "userId" : "build_gates",
#     "title": "7월 12일 일기2",
#     "content" : "한게 없다 하..2"
# }

# POST {{server}}show_profile/
# content-type: application/json

# {
#     "userId": "test12345" 
# }

# POST {{server}}show_profile/
# content-type: application/json

# {
#     "userId": "build__gates" 
# }

# POST {{server}}signup/
# content-type: application/json

# {
#   "userId": "test12345",
#   "password":"1234",
#    "username" : "DgitalKaimera"
# }



# POST {{server}}signup/
# content-type: application/json

# {
#     "username": "adore",
#     "userId" : "mom",
#     "password" : "Qweasd123" 
# }


# POST {{server}}modify_profile/
# content-type: application/json

# {
#     "userId": "build__gates",
#     "type" : "hobby",
#     "content": "Cube" 
# }

# POST {{server}}modify_profile/
# content-type: application/json

# {
#     "userId": "test12345",
#     "type" : "username",
#     "content": "KING" 
# }

# POST {{server}}modify_text/
# content-type: application/json

# {
#     "title": "sfsdfd",
#     "type" : "content",
#     "what": "우와" 
# }

# POST {{server}}modify_text/
# content-type: application/json

# {
#     "title": "7월 11일 일기",
#     "type" : "title",
#     "what": "7월 11일 일기" 
# }

# POST {{server}}delete_text/
# content-type: application/json

# {
#     "userId": "build_gates",
#     "title": "7월 12일 일기2" 
# }


# POST {{server}}delete_profile/
# content-type: application/json

# {
#     "userId": "build__gates11" 
# }

# POST {{server}}modify_user/
# content-type: application/json

# {
#     "userId": "build__gates12",
#     "type" : "password",
#     "what" : "sk1445adfd"
# }

# POST {{server}}modify_text/
# content-type: application/json

# {
#     "title": "없는 제목",
#     "type" : "content",
#     "what" : "의미없는 내용"
# }

# POST {{server}}add_friend/
# content-type: application/json

# {
#     "userId": "AbraStone",
#     "follow" : "DAD"

# }


# POST {{server}}signup/
# content-type: application/json

# {
#     "username": "Dad",
#     "userId" : "DAD",
#     "password" : "Qweasd123" 
# }


# POST {{server}}show_all_write/
# content-type: application/json

# {
#     "userId": "build_gates" 
# }


# POST {{server}}Get_Following/
# content-type: application/json

# {
#     "userId": "AbraStone" 
# }

# POST {{server}}Get_Followers/
# content-type: application/json

# {
#     "userId": "mom" 
# }

# POST {{server}}kakao_signup/
# content-type: application/json

# {
#     "userId": "icp1481" 
# }


POST {{server}}show_all_friend/
content-type: application/json

{
    "userId": "AbraStone" 
}