@server = http://localhost:3000/

# POST {{server}}write/
# content-type: application/json

# {
#     "title": "테스트_게시글1",
#     "content" : "내용입니다 이게 뭐지"
# }

# POST {{server}}show_profile/
# content-type: application/json

# {
#     "userId": "build__gates2" 
# }

# POST {{server}}show_profile/
# content-type: application/json

# {
#     "userId": "build__gates" 
# }

# POST {{server}}add_profile/
# content-type: application/json

# {
#   "userId": "build__gates",
#   "birth": "2002-06-17",
#   "hobby": "Magic"
# }



# POST {{server}}signup/
# content-type: application/json

# {
#     "username": "Seonkyu",
#     "userId" : "build__gates11",
#     "password" : "Qweasd123" 
# }


# POST {{server}}modify_profile/
# content-type: application/json

# {
#     "userId": "build__gates",
#     "type" : "hobby",
#     "content": "Cube" 
# }

# POST {{server}}modify_profile/
# content-type: application/json

# {
#     "userId": "build__gates",
#     "type" : "birth",
#     "content": "2002-01-01" 
# }

# POST {{server}}modify_text/
# content-type: application/json

# {
#     "title": "sfsdfd",
#     "type" : "content",
#     "what": "우와" 
# }

POST {{server}}modify_text/
content-type: application/json

{
    "title": "7월 11일 일기",
    "type" : "title",
    "what": "7월 11일 일기" 
}

# POST {{server}}delete_text/
# content-type: application/json

# {
#     "title": "etstd" 
# }

# POST {{server}}delete_profile/
# content-type: application/json

# {
#     "userId": "build__gates11" 
# }